### ISSUE TITLE
Can't seem to find 'ext install Angular-BeastCode'

### ISSUE THREAD

**Issue by jjnxpct** [anibalsanchez/VSCode-Joomla-Snippets#2]
Hi! I was trying to install this snippet extension but the 'Angular-BeastCode' does not exist anymore? Has something changed?

Kind regards,
Jip

**Comment by anibalsanchez** [comment]
Hi,

The extension is not related to 'Angular-BeastCode'. It seems that the issue is misplaced.

Please, clarify if the issue is about VSCode-Joomla-Snippets. I'm closing the issue in the meantime.

**Comment by jjnxpct** [comment]
In the readme of this rep:

Installation (Windows, Linux):

- Launch VS Code
- Quick Open (Ctrl-Shift-P)
- Enter the following command and press enter: 'ext install Angular-BeastCode'
- Choose extension (Author: Mikael Morlund)
- Reload VS Code

So maybe the readme is messed up?

**Comment by anibalsanchez** [comment]
Yes, the README comes from the original repo that I duplicated to create this extension.

**Comment by jjnxpct** [comment]
OK, thanks!

**Comment by anibalsanchez** [comment]
For future reference, the last version has this issue fixed: https://marketplace.visualstudio.com/items?itemName=AnibalSanchez.vs-code-joomla-snippets
